# Generated by Django 4.2 on 2024-05-13 14:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detectorists', '0001_initial'),
        ('favorites', '0002_alter_favorite_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('owner', 'detectorist')},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='post',
        ),
    ]
